Modify build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,41 +3,39 @@
 set -x              # Print command traces before executing command
 trap 'exit 1' ERR   # Exit script with error if command fails
 
-# Validate that docker exists
+cd $(dirname "${BASH_SOURCE[0]}")
+
 if [[ -z $(which docker) ]]; then
     echo "Missing docker client which is required for building, testing and pushing."
     exit 2
 fi
 
-# Set working directory to project root
-cd $(dirname "${BASH_SOURCE[0]}")
 
-# Declarations
 declare IMAGE_NAME="bachelorthesis/nodejs"
 
-# if not run as root user, docker needs sudo
-if [[ $EUID -ne 0 ]]; then
-    alias docker='sudo docker'
-fi
 
-# Build docker image
 function build {
     docker build -t $IMAGE_NAME .
 }
 
-# Test docker image
+
 function test {
+
 	docker history $IMAGE_NAME 2> /dev/null
     if [ $? -eq 1 ]; then
         echo "Cant test $IMAGE_NAME, the image does not exist."
         exit 2
     fi
     
-    #Run tests
+    if [[ -z $(which bats) ]]; then
+        echo "Missing bats, which is required for testing."
+        exit 2
+    fi
+    
     bats test/
 }
 
-# Push docker image to docker hub
+
 function push {
 	docker history $IMAGE_NAME 2> /dev/null
 
@@ -50,13 +48,22 @@ function push {
     [ -z "$DOCKER_USER" ]     && { echo "Need to set DOCKER_USER";     exit 1; }
     [ -z "$DOCKER_PASSWORD" ] && { echo "Need to set DOCKER_PASSWORD"; exit 1; }
 
-    sudo docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
-    sudo docker push $IMAGE_NAME
+    if [[ $EUID -ne 0 ]]; then
+        sudo docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
+        sudo docker push $IMAGE_NAME
+    else
+        docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
+        docker push $IMAGE_NAME
+    fi
 }
 
-# Handle user input, if no arguments are given, run all functions.
-# Valid arguments are: make_rootfs, build, test and push
+
+#
+# Handle input
+#
+
 actions=("$@")
+
 if [ ${#actions[@]} -eq 0 ]; then
     actions=(build test push)
 fi
@@ -74,9 +81,5 @@ for action in "${actions[@]}"; do
         push)
             push
             ;;
-         
-        *)
-            echo $"Usage: $0 {build || test || push}"
-            exit 1
     esac
 done
